# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:8080/rest/reader/1234/events
#POST https://access-control-203411.appspot.com/rest/reader/1234/events
Content-Type: application/json

{
    "timestamp": 1526291678,
    "tag_id": "243F4AD56",
    "signature": "9234E84CBA42"
}

###